name: Git Checkout
on: [push]

jobs:
    checkout-and-display-fles:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before Checkout
              run: ls -a
            - name: Checkout the Repository
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
                git fetch origin
                git checkout main
            - name: List Files After Checkout
              run: ls -a
    checkout-with-actions:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before Checkout with Actions
              run: ls -a
              ## Checkout using actions checkout action
            - name: Checkout Repository with Actions
              uses: actions/checkout@v3
            - name: List Files After Checkout with Actions
              run: ls -a