name: First Workflow
on: [push]

jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: Echo a string
              run: echo Hello, world!
            - name: Multiple commands
              run: |
                node -v
                npm -v
                echo "This is a multi-line command"
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View Software Versions
              run: sw_vers
    dependant-job:
        runs-on: windows-latest
        needs: run-shell-command
        steps:
            - name: echo a string
              run: Write-Output "Windows String"
            - name: Error Step
              run: doesnot exist